:---
- name: Update web servers
  hosts: web

  tasks:
  - name: Ensure web directory is created
    file:
     path: /home/centos/web-dir
     state: directory

  tasks:
   - name: Ensure file is downloaded
  get_url:
   url: https://filesamples.com/samples/document/txt/sample3.txt
   dest: /home/centos
...
